#!/bin/bash

user_name=$USER

current_date=$(date +"%Y-%m-%d")
current_time=$(date +"%H:%M:%S")

host=$(hostname)
source /etc/os-release
uptime=$(uptime -p)

echo "
System report generated by $user_name, $current_date, $current_time

#System information of the machine

System Information
-------------
Hostname:$host
OS: $PRETTY_NAME
Uptime:$uptime "

cpu_info=$(lscpu | grep "Model name:" | awk -F ': ' '{print $2}' | tr -d '[:space:]')
speed=$(sudo lshw -class processor | awk '/size:/{print $2; exit}')
Max_speed=$(sudo dmidecode -t processor | grep "Max Speed" | awk '{print $3,$4; exit}')
ram=$(sudo lshw -short -C memory | grep -i 'system memory' | awk '{print $3}')
disk=$(lsblk --output NAME,SIZE,TYPE,MOUNTPOINT,LABEL --exclude 7 | awk '!/loop/ {printf "%-8s %-8s %-4s %-8s %-7s %s\n", $1, $2, $3>
video_card=$(lspci -nnk | grep -i 'VGA' | awk -F': ' '{print $2}' | uniq)

#All necessary hardware information
echo "
Hardware Information
------------
CPU=$cpu_info
Speed=$speed
Max CPU Speed=$Max_speed
RAM=$ram
Disk(s)=$disk
Video=$video_card "

fqdn=$(hostname -f)
Ip_address=$(ip a show dev $(ip r | awk '/default/ {print $5}') | awk '/inet / {print $2}')
Gateway_address=$(ip r | awk '/default/ {print $3}')
DNS_Server=$(grep -E '^nameserver' /etc/resolv.conf | awk '{print $2}')
#information regarding network and IP addresses

Network_card=$(ip a show dev $(ip r | awk '/default/ {print $5}') | awk '/inet/ {print$7}')
IP_address=$(ip a show dev $(ip r | awk '/default/ {print $5}') | awk '/inet / {print $2}')

#providing network information including ip and host address

echo "
Network Information
------------
FQDN=$fqdn
Host Address=$Ip_address
Gateway IP=$Gateway_address
DNS Server=$DNS_Server
InterfaceName=$Network_card
IP Address=$IP_address"

Users=$(who | awk '{print $1}' | sort | uniq | paste -s -d ',')
disk_space=$(df -h)
process_count=$(ps -e | wc -l)
Load=$(uptime | awk -F'[a-z]:' '{print $2}')
Allocated_memory=$(free -h | awk '/^Mem:/ {print "Type\tTotal\tAvailable"; print $1 "\t" $2 "\t" $7}')
Network_ports=$(ss -tuln | awk 'BEGIN {print "State\tRecv-Q\tSend-Q\tLocal Address:Port\tPeer Address:Port"} /LISTEN/ {print $1 "\t"><1 "\t" $2 "\t" $3 "\t" $4 "\t\t" $5}')
UFW_rules=$(sudo ufw status numbered | grep -v 'Status: active')


#All system information with memeory and disk allocations

echo "
System Status
-----------
Users logged In=$Users
Disk Space=$disk_space
Process Count=$process_count
Load Averages=$Load
Memory Allocation=$Allocated_memory
Listening Network Ports=$Network_ports
UFW Rules=$UFW_rules"
